---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-python
  namespace: kooplex-veo
spec:
  hostname: postgres-python
  containers:
  - image: kooplex/k8plex-ei-jupyter-basic
    command:
      - sleep
      - infinity
    name: postgres-python
    env:
      - name: SCHEMA_PATH
        value: /mnt/repo/schema/
      - name: DB_PORT
        value: "5432"
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: pg-admin-ebi
            key: admin
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pg-admin-ebi
            key: adminpw
      - name: DB_HOST
        valueFrom:
          secretKeyRef:
            name: pg-admin-ebi
            key: dbhost
      - name: DB
        valueFrom:
          secretKeyRef:
            name: pg-admin-ebi
            key: db
    volumeMounts:
      - mountPath: /mnt
        name: pv-x
  volumes:
    - name: pv-x
      persistentVolumeClaim:
        claimName: pvc-raw

