kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-kooplex-postgres
  namespace: kooplex-veo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: nfs-client
